name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Yarn install
        uses: hexancore/yarn-ci-install@ba9baf131eba84b6c86efb46375a530a3098bb04

      # Publish package
      - name: Publish
        shell: bash
        run: |
          echo -e "\nnpmAuthToken: '${{ env.NODE_AUTH_TOKEN }}'" >> ./.yarnrc.yml
          yarn npm publish --provenance --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
