name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.HEXANCORE_BOT_TOKEN }}
        env:
          HEXANCORE_BOT_TOKEN: ${{ secrets.HEXANCORE_BOT_TOKEN }}

      - name: Yarn install
        uses: hexancore/yarn-ci-install@0.1.0

      # Publish package
      - name: Publish
        shell: bash
        run: |
          echo -e "\nnpmAuthToken: '${{ env.NODE_AUTH_TOKEN }}'" >> ./.yarnrc.yml
          yarn npm publish --provenance --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
