name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type (one of): patch, minor, major'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.HEXANCORE_BOT_TOKEN }}
        env:
          HEXANCORE_BOT_TOKEN: ${{ secrets.HEXANCORE_BOT_TOKEN }}

      - name: Yarn install
        uses: hexancore/yarn-ci-install@0.1.0

      - name: test
        uses: ./.github/actions/test

      # Publish package
      - name: Publish
        shell: bash
        run: |
          echo -e "\nnpmAuthToken: '${{ env.NODE_AUTH_TOKEN }}'" >> ./.yarnrc.yml
          yarn npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      #- name: publish
      #  uses: ./.github/actions/publish
